// ui/src/components/BottomBar.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { listen, type UnlistenFn } from "@tauri-apps/api/event";
  import { authState } from "../stores/auth.svelte";
  import { gameState } from "../stores/game.svelte";
  import { uiState } from "../stores/ui.svelte";
  import { instancesState } from "../stores/instances.svelte";
  import { Terminal, ChevronDown, Play, User, Check } from 'lucide-svelte';

  interface InstalledVersion {
    id: string;
    type: string;
  }

  let isVersionDropdownOpen = $state(false);
  let dropdownRef: HTMLDivElement;
  let installedVersions = $state<InstalledVersion[]>([]);
  let isLoadingVersions = $state(true);
  let downloadCompleteUnlisten: UnlistenFn | null = null;
  let versionDeletedUnlisten: UnlistenFn | null = null;

  // Load installed versions on mount
  $effect(() => {
    loadInstalledVersions();
    setupEventListeners();
    return () => {
      if (downloadCompleteUnlisten) {
        downloadCompleteUnlisten();
      }
      if (versionDeletedUnlisten) {
        versionDeletedUnlisten();
      }
    };
  });

  async function setupEventListeners() {
    // Refresh list when a download completes
    downloadCompleteUnlisten = await listen("download-complete", () => {
      loadInstalledVersions();
    });
    // Refresh list when a version is deleted
    versionDeletedUnlisten = await listen("version-deleted", () => {
      loadInstalledVersions();
    });
  }

  async function loadInstalledVersions() {
    if (!instancesState.activeInstanceId) {
      installedVersions = [];
      isLoadingVersions = false;
      return;
    }
    isLoadingVersions = true;
    try {
      installedVersions = await invoke<InstalledVersion[]>("list_installed_versions", {
        instanceId: instancesState.activeInstanceId,
      });
      // If no version is selected but we have installed versions, select the first one
      if (!gameState.selectedVersion && installedVersions.length > 0) {
        gameState.selectedVersion = installedVersions[0].id;
      }
    } catch (e) {
      console.error("Failed to load installed versions:", e);
    } finally {
      isLoadingVersions = false;
    }
  }

  let versionOptions = $derived(
    isLoadingVersions 
      ? [{ id: "loading", type: "loading", label: "Loading..." }]
      : installedVersions.length === 0
        ? [{ id: "empty", type: "empty", label: "No versions installed" }]
        : installedVersions.map(v => ({
            ...v,
            label: `${v.id}${v.type !== 'release' ? ` (${v.type})` : ''}`
          }))
  );

  function selectVersion(id: string) {
    if (id !== "loading" && id !== "empty") {
      gameState.selectedVersion = id;
      isVersionDropdownOpen = false;
    }
  }

  function handleClickOutside(e: MouseEvent) {
    if (dropdownRef && !dropdownRef.contains(e.target as Node)) {
      isVersionDropdownOpen = false;
    }
  }

  $effect(() => {
    if (isVersionDropdownOpen) {
      document.addEventListener('click', handleClickOutside);
      return () => document.removeEventListener('click', handleClickOutside);
    }
  });

  function getVersionTypeColor(type: string) {
    switch (type) {
      case 'fabric': return 'text-indigo-400';
      case 'forge': return 'text-orange-400';
      case 'snapshot': return 'text-amber-400';
      case 'modpack': return 'text-purple-400';
      default: return 'text-emerald-400';
    }
  }
</script>

<div
  class="h-20 bg-white/80 dark:bg-[#09090b]/90 border-t dark:border-white/10 border-black/5 flex items-center px-8 justify-between z-20 backdrop-blur-md"
>
  <!-- Account Area -->
  <div class="flex items-center gap-6">
    <div
      class="group flex items-center gap-4 cursor-pointer"
      onclick={() => authState.openLoginModal()}
      role="button"
      tabindex="0"
      onkeydown={(e) => e.key === "Enter" && authState.openLoginModal()}
    >
      <div
        class="w-10 h-10 rounded-sm bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 flex items-center justify-center overflow-hidden transition-all group-hover:border-zinc-400 dark:group-hover:border-zinc-500"
      >
        {#if authState.currentAccount}
          <img
            src={`https://minotar.net/avatar/${authState.currentAccount.username}/48`}
            alt={authState.currentAccount.username}
            class="w-full h-full"
          />
        {:else}
          <User size={20} class="text-zinc-400" />
        {/if}
      </div>
      <div>
        <div class="font-bold dark:text-white text-gray-900 text-sm group-hover:text-black dark:group-hover:text-zinc-200 transition-colors">
          {authState.currentAccount ? authState.currentAccount.username : "Login Account"}
        </div>
        <div class="text-[10px] uppercase tracking-wider dark:text-zinc-500 text-gray-500 flex items-center gap-2">
          {#if authState.currentAccount}
            {#if authState.currentAccount.type === "Microsoft"}
              {#if authState.currentAccount.expires_at && authState.currentAccount.expires_at * 1000 < Date.now()}
                <span class="w-1.5 h-1.5 rounded-full bg-red-500"></span>
                <span class="text-red-400">Expired</span>
              {:else}
                <span class="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                Online
              {/if}
            {:else}
              <span class="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
              Offline
            {/if}
          {:else}
            <span class="w-1.5 h-1.5 rounded-full bg-zinc-400"></span>
            Guest
          {/if}
        </div>
      </div>
    </div>
    
    <div class="h-8 w-px dark:bg-white/10 bg-black/10"></div>
    
    <!-- Console Toggle -->
    <button
      class="text-xs font-mono dark:text-zinc-500 text-gray-500 dark:hover:text-white hover:text-black transition-colors flex items-center gap-2 px-2 py-1 rounded-sm hover:bg-black/5 dark:hover:bg-white/5"
      onclick={() => uiState.toggleConsole()}
    >
      <Terminal size={14} />
      {uiState.showConsole ? "HIDE LOGS" : "SHOW LOGS"}
    </button>
  </div>

  <!-- Action Area -->
  <div class="flex items-center gap-4">
    <div class="flex flex-col items-end mr-2">
      <!-- Custom Version Dropdown -->
      <div class="relative" bind:this={dropdownRef}>
        <button
            type="button"
            onclick={() => isVersionDropdownOpen = !isVersionDropdownOpen}
            disabled={installedVersions.length === 0 && !isLoadingVersions}
            class="flex items-center justify-between gap-2 w-56 px-4 py-2.5 text-left
                   dark:bg-zinc-900 bg-zinc-50 border dark:border-zinc-700 border-zinc-300 rounded-md 
                   text-sm font-mono dark:text-white text-gray-900
                   dark:hover:border-zinc-600 hover:border-zinc-400 
                   focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30
                   transition-colors cursor-pointer outline-none
                   disabled:opacity-50 disabled:cursor-not-allowed"
          >
          <span class="truncate">
            {#if isLoadingVersions}
              Loading...
            {:else if installedVersions.length === 0}
              No versions installed
            {:else}
              {gameState.selectedVersion || "Select version"}
            {/if}
          </span>
          <ChevronDown 
            size={14} 
            class="shrink-0 dark:text-zinc-500 text-zinc-400 transition-transform duration-200 {isVersionDropdownOpen ? 'rotate-180' : ''}" 
          />
        </button>

        {#if isVersionDropdownOpen && installedVersions.length > 0}
          <div 
            class="absolute z-50 w-full mt-1 py-1 dark:bg-zinc-900 bg-white border dark:border-zinc-700 border-zinc-300 rounded-md shadow-xl
                   max-h-72 overflow-y-auto animate-in fade-in slide-in-from-top-1 duration-150 bottom-full mb-1 right-0"
          >
            {#each versionOptions as version}
              <button
                type="button"
                onclick={() => selectVersion(version.id)}
                disabled={version.id === "loading" || version.id === "empty"}
                class="w-full flex items-center justify-between px-3 py-2 text-sm font-mono text-left
                       transition-colors outline-none
                       {version.id === gameState.selectedVersion 
                         ? 'bg-indigo-600 text-white' 
                         : 'dark:text-zinc-300 text-gray-700 dark:hover:bg-zinc-800 hover:bg-zinc-100'}
                       {version.id === 'loading' || version.id === 'empty' ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}"
              >
                <span class="truncate flex items-center gap-2">
                  {version.id}
                  {#if version.type && version.type !== 'release' && version.type !== 'loading' && version.type !== 'empty'}
                    <span class="text-[10px] uppercase {version.id === gameState.selectedVersion ? 'text-white/70' : getVersionTypeColor(version.type)}">
                      {version.type}
                    </span>
                  {/if}
                </span>
                {#if version.id === gameState.selectedVersion}
                  <Check size={14} class="shrink-0 ml-2" />
                {/if}
              </button>
            {/each}
          </div>
        {/if}
      </div>
    </div>

    <button
      onclick={() => gameState.startGame()}
      disabled={installedVersions.length === 0 || !gameState.selectedVersion}
      class="bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed text-white h-14 px-10 rounded-sm transition-all duration-200 hover:scale-[1.02] active:scale-[0.98] shadow-lg shadow-emerald-500/20 flex items-center gap-3 font-bold text-lg tracking-widest uppercase"
    >
      <Play size={24} fill="currentColor" />
      <span>Launch</span>
    </button>
  </div>
</div>

// packages/ui/src/components/bottom-bar.tsx
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import { Play, User, XIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { listInstalledVersions, startGame } from "@/client";
import { cn } from "@/lib/utils";
import { useAuthStore } from "@/models/auth";
import { useInstanceStore } from "@/models/instance";
import { useGameStore } from "@/stores/game-store";
import { LoginModal } from "./login-modal";
import { Button } from "./ui/button";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";
import { Spinner } from "./ui/spinner";

interface InstalledVersion {
  id: string;
  type: string;
}

export function BottomBar() {
  const authStore = useAuthStore();
  const gameStore = useGameStore();
  const instancesStore = useInstanceStore();

  const [isLaunched, setIsLaunched] = useState<boolean>(false);
  const gameUnlisten = useRef<UnlistenFn | null>(null);
  const [isLaunching, setIsLaunching] = useState<boolean>(false);
  const [selectedVersion, setSelectedVersion] = useState<string | null>(null);
  const [installedVersions, setInstalledVersions] = useState<
    InstalledVersion[]
  >([]);
  const [isLoadingVersions, setIsLoadingVersions] = useState(true);
  const [showLoginModal, setShowLoginModal] = useState(false);

  const loadInstalledVersions = useCallback(async () => {
    if (!instancesStore.activeInstance) {
      setInstalledVersions([]);
      setIsLoadingVersions(false);
      return;
    }

    setIsLoadingVersions(true);
    try {
      const versions = await listInstalledVersions(
        instancesStore.activeInstance.id,
      );

      const installed = versions || [];
      setInstalledVersions(installed);

      // If no version is selected but we have installed versions, select the first one
      if (!gameStore.selectedVersion && installed.length > 0) {
        gameStore.setSelectedVersion(installed[0].id);
      }
    } catch (error) {
      console.error("Failed to load installed versions:", error);
    } finally {
      setIsLoadingVersions(false);
    }
  }, [
    instancesStore.activeInstance,
    gameStore.selectedVersion,
    gameStore.setSelectedVersion,
  ]);

  useEffect(() => {
    loadInstalledVersions();

    // Listen for backend events that should refresh installed versions.
    let unlistenDownload: UnlistenFn | null = null;
    let unlistenVersionDeleted: UnlistenFn | null = null;

    (async () => {
      try {
        unlistenDownload = await listen("download-complete", () => {
          loadInstalledVersions();
        });
      } catch (err) {
        // best-effort: do not break UI if listening fails
        // eslint-disable-next-line no-console
        console.warn("Failed to attach download-complete listener:", err);
      }

      try {
        unlistenVersionDeleted = await listen("version-deleted", () => {
          loadInstalledVersions();
        });
      } catch (err) {
        // eslint-disable-next-line no-console
        console.warn("Failed to attach version-deleted listener:", err);
      }
    })();

    return () => {
      try {
        if (unlistenDownload) unlistenDownload();
      } catch {
        // ignore
      }
      try {
        if (unlistenVersionDeleted) unlistenVersionDeleted();
      } catch {
        // ignore
      }
    };
  }, [loadInstalledVersions]);

  const handleStartGame = async () => {
    if (!selectedVersion) {
      toast.info("Please select a version!");
      return;
    }

    if (!instancesStore.activeInstance) {
      toast.info("Please select an instance first!");
      return;
    }

    try {
      gameUnlisten.current = await listen("game-exited", () => {
        setIsLaunched(false);
      });
    } catch (error) {
      toast.warning(`Failed to listen to game-exited event: ${error}`);
    }

    setIsLaunching(true);
    try {
      await startGame(instancesStore.activeInstance?.id, selectedVersion);
      setIsLaunched(true);
    } catch (error) {
      console.error(`Failed to start game: ${error}`);
      toast.error(`Failed to start game: ${error}`);
    } finally {
      setIsLaunching(false);
    }
  };

  const getVersionTypeColor = (type: string) => {
    switch (type) {
      case "release":
        return "bg-emerald-500";
      case "snapshot":
        return "bg-amber-500";
      case "old_beta":
        return "bg-rose-500";
      case "old_alpha":
        return "bg-violet-500";
      default:
        return "bg-gray-500";
    }
  };

  const versionOptions = useMemo(
    () =>
      installedVersions.map((v) => ({
        label: `${v.id}${v.type !== "release" ? ` (${v.type})` : ""}`,
        value: v.id,
        type: v.type,
      })),
    [installedVersions],
  );

  const renderButton = () => {
    if (!authStore.account) {
      return (
        <Button
          className="px-4 py-2"
          size="lg"
          onClick={() => setShowLoginModal(true)}
        >
          <User /> Login
        </Button>
      );
    }

    return isLaunched ? (
      <Button
        variant="destructive"
        onClick={() => {
          toast.warning(
            "Minecraft Process will not be terminated, please close it manually.",
          );
          setIsLaunched(false);
        }}
      >
        <XIcon />
        Game started
      </Button>
    ) : (
      <Button
        className={cn(
          "px-4 py-2 shadow-xl",
          "bg-emerald-600! hover:bg-emerald-500!",
        )}
        size="lg"
        onClick={handleStartGame}
        disabled={isLaunching}
      >
        {isLaunching ? <Spinner /> : <Play />}
        Start
      </Button>
    );
  };

  return (
    <div className="absolute bottom-0 left-0 right-0 bg-linear-to-t from-black/30 via-transparent to-transparent p-4 z-10">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between bg-white/5 dark:bg-black/20 backdrop-blur-xl border border-white/10 dark:border-white/5 p-3 shadow-lg">
          <div className="flex items-center gap-4">
            <div className="flex flex-col">
              <span className="text-xs font-mono text-zinc-400 uppercase tracking-wider">
                Active Instance
              </span>
              <span className="text-sm font-medium text-white">
                {instancesStore.activeInstance?.name || "No instance selected"}
              </span>
            </div>

            <Select
              items={versionOptions}
              onValueChange={setSelectedVersion}
              disabled={isLoadingVersions}
            >
              <SelectTrigger className="max-w-48">
                <SelectValue
                  placeholder={
                    isLoadingVersions
                      ? "Loading versions..."
                      : "Please select a version"
                  }
                />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {versionOptions.map((item) => (
                    <SelectItem
                      key={item.value}
                      value={item.value}
                      className={getVersionTypeColor(item.type)}
                    >
                      {item.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-center gap-3">{renderButton()}</div>
        </div>
      </div>

      <LoginModal
        open={showLoginModal}
        onOpenChange={() => setShowLoginModal(false)}
      />
    </div>
  );
}
