// ui/src/components/InstancesView.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { instancesState } from "../stores/instances.svelte";
  import { Plus, Trash2, Edit2, Copy, Check, X } from "lucide-svelte";
  import type { Instance } from "../types";
  import InstanceCreationModal from "./InstanceCreationModal.svelte";
  import InstanceEditorModal from "./InstanceEditorModal.svelte";

  let showCreateModal = $state(false);
  let showEditModal = $state(false);
  let showDeleteConfirm = $state(false);
  let showDuplicateModal = $state(false);
  let selectedInstance: Instance | null = $state(null);
  let editingInstance: Instance | null = $state(null);
  let newInstanceName = $state("");
  let duplicateName = $state("");

  onMount(() => {
    instancesState.loadInstances();
  });

  function handleCreate() {
    showCreateModal = true;
  }

  function handleEdit(instance: Instance) {
    editingInstance = instance;
  }

  function handleDelete(instance: Instance) {
    selectedInstance = instance;
    showDeleteConfirm = true;
  }

  function handleDuplicate(instance: Instance) {
    selectedInstance = instance;
    duplicateName = `${instance.name} (Copy)`;
    showDuplicateModal = true;
  }

  async function confirmDelete() {
    if (!selectedInstance) return;
    await instancesState.deleteInstance(selectedInstance.id);
    showDeleteConfirm = false;
    selectedInstance = null;
  }

  async function confirmDuplicate() {
    if (!selectedInstance || !duplicateName.trim()) return;
    await instancesState.duplicateInstance(selectedInstance.id, duplicateName.trim());
    showDuplicateModal = false;
    selectedInstance = null;
    duplicateName = "";
  }

  function formatDate(timestamp: number): string {
    return new Date(timestamp * 1000).toLocaleDateString();
  }

  function formatLastPlayed(timestamp: number): string {
    const date = new Date(timestamp * 1000);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    
    if (days === 0) return "Today";
    if (days === 1) return "Yesterday";
    if (days < 7) return `${days} days ago`;
    return date.toLocaleDateString();
  }
</script>

<div class="h-full flex flex-col gap-4 p-6 overflow-y-auto">
  <div class="flex items-center justify-between">
    <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Instances</h1>
    <button
      onclick={handleCreate}
      class="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
    >
      <Plus size={18} />
      Create Instance
    </button>
  </div>

  {#if instancesState.instances.length === 0}
    <div class="flex-1 flex items-center justify-center">
      <div class="text-center text-gray-500 dark:text-gray-400">
        <p class="text-lg mb-2">No instances yet</p>
        <p class="text-sm">Create your first instance to get started</p>
      </div>
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {#each instancesState.instances as instance (instance.id)}
        <div
          role="button"
          tabindex="0"
          class="relative p-4 bg-gray-100 dark:bg-gray-800 rounded-lg border-2 transition-all cursor-pointer hover:border-blue-500 {instancesState.activeInstanceId === instance.id
            ? 'border-blue-500'
            : 'border-transparent'}"
          onclick={() => instancesState.setActiveInstance(instance.id)}
          onkeydown={(e) => e.key === "Enter" && instancesState.setActiveInstance(instance.id)}
        >
          {#if instancesState.activeInstanceId === instance.id}
            <div class="absolute top-2 right-2">
              <div class="w-3 h-3 bg-blue-500 rounded-full"></div>
            </div>
          {/if}

          <div class="flex items-start justify-between mb-2">
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
              {instance.name}
            </h3>
            <div class="flex gap-1">
              <button
                type="button"
                onclick={(e) => {
                  e.stopPropagation();
                  handleEdit(instance);
                }}
                class="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                title="Edit"
              >
                <Edit2 size={16} class="text-gray-600 dark:text-gray-400" />
              </button>
              <button
                type="button"
                onclick={(e) => {
                  e.stopPropagation();
                  handleDuplicate(instance);
                }}
                class="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                title="Duplicate"
              >
                <Copy size={16} class="text-gray-600 dark:text-gray-400" />
              </button>
              <button
                type="button"
                onclick={(e) => {
                  e.stopPropagation();
                  handleDelete(instance);
                }}
                class="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                title="Delete"
              >
                <Trash2 size={16} class="text-red-600 dark:text-red-400" />
              </button>
            </div>
          </div>

          <div class="space-y-1 text-sm text-gray-600 dark:text-gray-400">
            {#if instance.version_id}
              <p>Version: <span class="font-medium">{instance.version_id}</span></p>
            {:else}
              <p class="text-gray-400">No version selected</p>
            {/if}

            {#if instance.mod_loader && instance.mod_loader !== "vanilla"}
              <p>
                Mod Loader: <span class="font-medium capitalize">{instance.mod_loader}</span>
                {#if instance.mod_loader_version}
                  <span class="text-gray-500">({instance.mod_loader_version})</span>
                {/if}
              </p>
            {/if}

            <p>Created: {formatDate(instance.created_at)}</p>

            {#if instance.last_played}
              <p>Last played: {formatLastPlayed(instance.last_played)}</p>
            {/if}
          </div>

          {#if instance.notes}
            <p class="mt-2 text-sm text-gray-500 dark:text-gray-500 italic">
              {instance.notes}
            </p>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

<!-- Create Modal -->
<InstanceCreationModal isOpen={showCreateModal} onClose={() => (showCreateModal = false)} />

<!-- Instance Editor Modal -->
<InstanceEditorModal
  isOpen={editingInstance !== null}
  instance={editingInstance}
  onClose={() => {
    editingInstance = null;
  }}
/>

<!-- Delete Confirmation -->
{#if showDeleteConfirm && selectedInstance}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 w-96">
      <h2 class="text-xl font-bold mb-4 text-red-600 dark:text-red-400">Delete Instance</h2>
      <p class="mb-4 text-gray-700 dark:text-gray-300">
        Are you sure you want to delete "{selectedInstance.name}"? This action cannot be undone and will delete all game data for this instance.
      </p>
      <div class="flex gap-2 justify-end">
        <button
          onclick={() => {
            showDeleteConfirm = false;
            selectedInstance = null;
          }}
          class="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
        >
          Cancel
        </button>
        <button
          onclick={confirmDelete}
          class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
        >
          Delete
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- Duplicate Modal -->
{#if showDuplicateModal && selectedInstance}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 w-96">
      <h2 class="text-xl font-bold mb-4 text-gray-900 dark:text-white">Duplicate Instance</h2>
      <input
        type="text"
        bind:value={duplicateName}
        placeholder="New instance name"
        class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white mb-4"
        onkeydown={(e) => e.key === "Enter" && confirmDuplicate()}
      />
      <div class="flex gap-2 justify-end">
        <button
          onclick={() => {
            showDuplicateModal = false;
            selectedInstance = null;
            duplicateName = "";
          }}
          class="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
        >
          Cancel
        </button>
        <button
          onclick={confirmDuplicate}
          disabled={!duplicateName.trim()}
          class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          Duplicate
        </button>
      </div>
    </div>
  </div>
{/if}

// packages/ui/src/pages/instances-view.tsx
import { Copy, Edit2, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import InstanceCreationModal from "@/components/instance-creation-modal";
import InstanceEditorModal from "@/components/instance-editor-modal";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { toNumber } from "@/lib/tsrs-utils";
import { useInstancesStore } from "@/models/instances";
import type { Instance } from "../types/bindings/instance";

export function InstancesView() {
  const instancesStore = useInstancesStore();

  // Modal / UI state
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [showDuplicateModal, setShowDuplicateModal] = useState(false);

  // Selected / editing instance state
  const [selectedInstance, setSelectedInstance] = useState<Instance | null>(
    null,
  );
  const [editingInstance, setEditingInstance] = useState<Instance | null>(null);

  // Form fields
  const [duplicateName, setDuplicateName] = useState("");

  useEffect(() => {
    instancesStore.refresh();
  }, [instancesStore.refresh]);

  // Handlers to open modals
  const openCreate = () => {
    setShowCreateModal(true);
  };

  const openEdit = (instance: Instance) => {
    setEditingInstance({ ...instance });
    setShowEditModal(true);
  };

  const openDelete = (instance: Instance) => {
    setSelectedInstance(instance);
    setShowDeleteConfirm(true);
  };

  const openDuplicate = (instance: Instance) => {
    setSelectedInstance(instance);
    setDuplicateName(`${instance.name} (Copy)`);
    setShowDuplicateModal(true);
  };

  const confirmDelete = async () => {
    if (!selectedInstance) return;
    await instancesStore.delete(selectedInstance.id);
    setSelectedInstance(null);
    setShowDeleteConfirm(false);
  };

  const confirmDuplicate = async () => {
    if (!selectedInstance) return;
    const name = duplicateName.trim();
    if (!name) return;
    await instancesStore.duplicate(selectedInstance.id, name);
    setSelectedInstance(null);
    setDuplicateName("");
    setShowDuplicateModal(false);
  };

  const formatDate = (timestamp: number): string =>
    new Date(timestamp * 1000).toLocaleDateString();

  const formatLastPlayed = (timestamp: number): string => {
    const date = new Date(timestamp * 1000);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) return "Today";
    if (days === 1) return "Yesterday";
    if (days < 7) return `${days} days ago`;
    return date.toLocaleDateString();
  };

  return (
    <div className="h-full flex flex-col gap-4 p-6 overflow-y-auto">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
          Instances
        </h1>
        <Button
          type="button"
          onClick={openCreate}
          className="px-4 py-2 transition-colors"
        >
          <Plus size={18} />
          Create Instance
        </Button>
      </div>

      {instancesStore.instances.length === 0 ? (
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center text-gray-500 dark:text-gray-400">
            <p className="text-lg mb-2">No instances yet</p>
            <p className="text-sm">Create your first instance to get started</p>
          </div>
        </div>
      ) : (
        <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {instancesStore.instances.map((instance) => {
            const isActive = instancesStore.activeInstance?.id === instance.id;

            return (
              <li
                key={instance.id}
                onClick={() => instancesStore.setActiveInstance(instance)}
                onKeyDown={(e) =>
                  e.key === "Enter" &&
                  instancesStore.setActiveInstance(instance)
                }
                className={`relative p-4 text-left border-2 transition-all cursor-pointer hover:border-blue-500 ${
                  isActive ? "border-blue-500" : "border-transparent"
                } bg-gray-100 dark:bg-gray-800`}
              >
                {/* Instance Icon */}
                {instance.iconPath ? (
                  <div className="w-12 h-12 mb-3 rounded overflow-hidden">
                    <img
                      src={instance.iconPath}
                      alt={instance.name}
                      className="w-full h-full object-cover"
                    />
                  </div>
                ) : (
                  <div className="w-12 h-12 mb-3 rounded bg-linear-to-br from-blue-500 to-purple-600 flex items-center justify-center">
                    <span className="text-white font-bold text-lg">
                      {instance.name.charAt(0).toUpperCase()}
                    </span>
                  </div>
                )}

                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-1">
                  {instance.name}
                </h3>

                <div className="space-y-1 text-sm text-gray-600 dark:text-gray-400">
                  {instance.versionId ? (
                    <p className="truncate">Version: {instance.versionId}</p>
                  ) : (
                    <p className="text-gray-400">No version selected</p>
                  )}

                  {instance.modLoader && (
                    <p className="truncate">
                      Mod Loader:{" "}
                      <span className="capitalize">{instance.modLoader}</span>
                    </p>
                  )}

                  <p className="truncate">
                    Created: {formatDate(toNumber(instance.createdAt))}
                  </p>

                  {instance.lastPlayed && (
                    <p className="truncate">
                      Last played:{" "}
                      {formatLastPlayed(toNumber(instance.lastPlayed))}
                    </p>
                  )}
                </div>

                {/* Action Buttons */}
                <div className="mt-4 flex gap-2">
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      openEdit(instance);
                    }}
                    className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded text-sm transition-colors"
                  >
                    <Edit2 size={14} />
                    Edit
                  </button>

                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      openDuplicate(instance);
                    }}
                    className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded text-sm transition-colors"
                  >
                    <Copy size={14} />
                    Duplicate
                  </button>

                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      openDelete(instance);
                    }}
                    className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 bg-red-500 hover:bg-red-600 text-white rounded text-sm transition-colors"
                  >
                    <Trash2 size={14} />
                    Delete
                  </button>
                </div>
              </li>
            );
          })}
        </ul>
      )}

      <InstanceCreationModal
        open={showCreateModal}
        onOpenChange={setShowCreateModal}
      />

      <InstanceEditorModal
        open={showEditModal}
        instance={editingInstance}
        onOpenChange={(open) => {
          setShowEditModal(open);
          if (!open) setEditingInstance(null);
        }}
      />

      {/* Delete Confirmation */}
      <Dialog open={showDeleteConfirm} onOpenChange={setShowDeleteConfirm}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Instance</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete "{selectedInstance?.name}"? This
              action cannot be undone.
            </DialogDescription>
          </DialogHeader>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                setShowDeleteConfirm(false);
                setSelectedInstance(null);
              }}
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={confirmDelete}
              className="bg-red-600 text-white hover:bg-red-500"
            >
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Duplicate Modal */}
      <Dialog open={showDuplicateModal} onOpenChange={setShowDuplicateModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Duplicate Instance</DialogTitle>
            <DialogDescription>
              Provide a name for the duplicated instance.
            </DialogDescription>
          </DialogHeader>

          <div className="mt-4">
            <Input
              value={duplicateName}
              onChange={(e) => setDuplicateName(e.target.value)}
              placeholder="New instance name"
              onKeyDown={(e) => e.key === "Enter" && confirmDuplicate()}
            />
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                setShowDuplicateModal(false);
                setSelectedInstance(null);
                setDuplicateName("");
              }}
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={confirmDuplicate}
              disabled={!duplicateName.trim()}
            >
              Duplicate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
